In [4]:
import numpy as np

A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

c = np.dot(A, B)

print("行列の積の結果：")
print(c)

c_max = np.max(c)
print("行列の要素の最大値：")
print(c_max)

行列の積の結果：
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
行列の要素の最大値：
47
